// glass-dashboard/src/components/BoardEditor.jsx
import React, { useState } from 'react';
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';
import { Form, Button, Card } from 'react-bootstrap';

const BoardEditor = ({ onSave, onCancel, initialData = { title: '', content: '' } }) => {
   const [title, setTitle] = useState(initialData.title);
   const [content, setContent] = useState(initialData.content);

   const handleSubmit = (e) => {
      e.preventDefault();
      onSave({ title, content });
   };

   const modules = {
      toolbar: [
         [{ 'header': [1, 2, false] }],
         ['bold', 'italic', 'underline', 'strike', 'blockquote'],
         [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'indent': '-1' }, { 'indent': '+1' }],
         ['link', 'image'],
         ['clean']
      ],
   };

   const formats = [
      'header',
      'bold', 'italic', 'underline', 'strike', 'blockquote',
      'list', 'bullet', 'indent',
      'link', 'image'
   ];

   return (
      <Card className="glass-card p-4">
         <Form onSubmit={handleSubmit}>
            <Form.Group className="mb-3">
               <Form.Label>Title</Form.Label>
               <Form.Control
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="Enter title"
                  required
                  className="glass-input"
               />
            </Form.Group>

            <Form.Group className="mb-3">
               <Form.Label>Content</Form.Label>
               <ReactQuill
                  theme="snow"
                  value={content}
                  onChange={setContent}
                  modules={modules}
                  formats={formats}
                  style={{ height: '300px', marginBottom: '50px' }}
               />
            </Form.Group>

            <div className="d-flex justify-content-end gap-2 mt-5">
               <Button variant="secondary" onClick={onCancel}>Cancel</Button>
               <Button variant="primary" type="submit">Save</Button>
            </div>
         </Form>
      </Card>
   );
};

export default BoardEditor;

// glass-dashboard-vue/src/components/board/BoardEditor.vue
<template>
  <div class="q-pa-none">
    <q-form @submit="handleSubmit">
      <div class="q-mb-md">
        <div class="text-subtitle2 text-grey-8 q-mb-xs">Title</div>
        <q-input
          v-model="title"
          filled
          placeholder="Enter title"
          class="glass-input"
          bg-color="white"
          :rules="[val => !!val || 'Title is required']"
        />
      </div>

      <div class="q-mb-md">
        <div class="text-subtitle2 text-grey-8 q-mb-xs">Content</div>
        <q-editor
          v-model="content"
          min-height="300px"
          :toolbar="[
            ['bold', 'italic', 'strike', 'underline'],
            ['token', 'hr', 'link', 'custom_btn'],
            ['quote', 'unordered', 'ordered', 'outdent', 'indent'],
            ['undo', 'redo'],
            ['viewsource']
          ]"
          content-class="bg-white text-dark"
          toolbar-bg="grey-2"
          toolbar-text-color="dark"
        />
      </div>

      <div class="row justify-end q-gutter-sm q-mt-lg">
        <q-btn flat label="Cancel" color="grey-8" @click="$emit('cancel')" />
        <q-btn type="submit" label="Save" color="primary" unelevated />
      </div>
    </q-form>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  initialData: {
    type: Object,
    default: () => ({ title: '', content: '' })
  }
})

const emit = defineEmits(['save', 'cancel'])

const title = ref(props.initialData.title || '')
const content = ref(props.initialData.content || '')

const handleSubmit = () => {
  emit('save', { title: title.value, content: content.value })
}
</script>

<style scoped>
.glass-card {
  background: rgba(30, 30, 47, 0.8);
  backdrop-filter: blur(10px);
  border-radius: 16px;
}

.glass-input :deep(.q-field__control) {
  background: rgba(255, 255, 255, 0.05);
}
</style>
