// glass-dashboard-vue/src/components/Diary.vue
<template>
  <div class="q-pa-md full-height">
    <div class="row q-col-gutter-md full-height">
      <!-- Input Section -->
      <div class="col-12 col-md-4">
        <q-card class="glass-card full-height column">
          <q-card-section class="bg-primary text-white q-py-md">
            <div class="text-h6 text-weight-bold flex items-center">
              <q-icon name="edit_note" class="q-mr-sm" />
              Write Diary
            </div>
            <div class="text-caption text-white" style="opacity: 0.8">
              {{ new Date().toLocaleDateString('default', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) }}
            </div>
          </q-card-section>

          <q-card-section class="col column q-pa-md">
            <q-input
              v-model="content"
              type="textarea"
              filled
              placeholder="How was your day?"
              class="col glass-input"
              bg-color="white"
              input-style="height: 100%; resize: none;"
            />
            <q-btn
              color="primary"
              class="full-width q-mt-md shadow-2"
              icon="save"
              label="Save Entry"
              @click="saveEntry"
              unelevated
              size="lg"
            />
          </q-card-section>
        </q-card>
      </div>

      <!-- List Section -->
      <div class="col-12 col-md-8">
        <q-card class="glass-card full-height column">
          <q-card-section class="bg-white text-primary q-py-sm border-bottom">
            <div class="text-h6 text-weight-bold flex items-center">
              <q-icon name="history_edu" class="q-mr-sm" />
              Your Stories
            </div>
          </q-card-section>

          <q-card-section class="col q-pa-none scroll">
            <q-timeline color="secondary" class="q-pa-md">
              <q-timeline-entry
                v-for="entry in entries"
                :key="entry.id"
                :title="new Date(entry.date).toLocaleDateString()"
                :subtitle="new Date(entry.date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })"
                icon="book"
              >
                <q-card flat bordered class="bg-white">
                  <q-card-section>
                    <div class="text-body1" style="white-space: pre-wrap;">{{ entry.content }}</div>
                  </q-card-section>
                  <q-card-actions align="right">
                    <q-btn flat round dense color="negative" icon="delete" size="sm" @click="deleteEntry(entry.id)" />
                  </q-card-actions>
                </q-card>
              </q-timeline-entry>
            </q-timeline>

            <div v-if="entries.length === 0" class="flex flex-center full-height text-grey-6 column">
              <q-icon name="auto_stories" size="4rem" class="q-mb-md opacity-50" />
              <div class="text-h6">No entries yet</div>
              <div class="text-subtitle2">Start writing your first diary entry!</div>
            </div>
          </q-card-section>
        </q-card>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import axios from 'axios'

const entries = ref([])
const content = ref('')
const API_URL = '/api/diary'

const fetchEntries = async () => {
  try {
    const response = await axios.get(API_URL)
    if (Array.isArray(response.data)) {
      entries.value = response.data.sort((a, b) => new Date(b.date) - new Date(a.date))
    } else {
      entries.value = []
    }
  } catch (error) {
    console.error('Error fetching diary entries:', error)
  }
}

const saveEntry = async () => {
  if (!content.value.trim()) return

  try {
    const response = await axios.post(API_URL, {
      content: content.value,
      date: new Date().toISOString()
    })
    entries.value.unshift(response.data)
    content.value = ''
  } catch (error) {
    console.error('Error saving diary entry:', error)
  }
}

const deleteEntry = async (id) => {
  try {
    await axios.delete(`${API_URL}/${id}`)
    entries.value = entries.value.filter(entry => entry.id !== id)
  } catch (error) {
    console.error('Error deleting diary entry:', error)
  }
}

onMounted(() => {
  fetchEntries()
})
</script>

<style scoped>
.glass-card {
  background: rgba(255, 255, 255, 0.9);
  backdrop-filter: blur(10px);
  border-radius: 16px;
}
</style>

// glass-dashboard/src/components/Diary.jsx
import React, { useState, useEffect } from 'react';
import { Card, Form, Button, ListGroup } from 'react-bootstrap';
import { Save, Trash2 } from 'lucide-react';

const Diary = () => {
   const [entries, setEntries] = useState([]);
   const [content, setContent] = useState('');
   const API_URL = '/api/diary';

   useEffect(() => {
      fetchEntries();
   }, []);

   const fetchEntries = async () => {
      try {
         const response = await fetch(API_URL, { credentials: 'include' });
         if (response.ok) {
            const data = await response.json();
            if (Array.isArray(data)) {
               // Sort by date descending
               const sorted = data.sort((a, b) => new Date(b.date) - new Date(a.date));
               setEntries(sorted);
            } else {
               setEntries([]);
            }
         }
      } catch (error) {
         console.error('Error fetching diary entries:', error);
      }
   };

   const saveEntry = async () => {
      if (!content.trim()) return;

      try {
         const response = await fetch(API_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ content: content, date: new Date().toISOString() }),
            credentials: 'include'
         });
         if (response.ok) {
            const newEntry = await response.json();
            setEntries([newEntry, ...entries]);
            setContent('');
         }
      } catch (error) {
         console.error('Error saving diary entry:', error);
      }
   };

   const deleteEntry = async (id) => {
      try {
         const response = await fetch(`${API_URL}/${id}`, {
            method: 'DELETE',
            credentials: 'include'
         });
         if (response.ok) {
            setEntries(entries.filter(entry => entry.id !== id));
         }
      } catch (error) {
         console.error('Error deleting diary entry:', error);
      }
   };

   return (
      <Card className="h-100 shadow-sm">
         <Card.Header className="bg-white border-bottom-0 pt-4 pb-0">
            <h5 className="mb-0 fw-bold text-secondary">Diary</h5>
         </Card.Header>
         <Card.Body className="d-flex flex-column">
            <Form.Group className="mb-3">
               <Form.Control
                  as="textarea"
                  rows={4}
                  placeholder="Write your thoughts..."
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  className="mb-2"
                  style={{ resize: 'none' }}
               />
               <Button variant="purple" className="w-100 d-flex align-items-center justify-content-center gap-2" onClick={saveEntry} style={{ backgroundColor: '#6f42c1', color: 'white' }}>
                  <Save size={18} /> Save Entry
               </Button>
            </Form.Group>

            <div className="flex-grow-1 overflow-auto custom-scrollbar" style={{ maxHeight: '400px' }}>
               {entries.map(entry => (
                  <Card key={entry.id} className="mb-3 border bg-light">
                     <Card.Body className="p-3">
                        <div className="d-flex justify-content-between align-items-start mb-2">
                           <small className="text-muted">{new Date(entry.date).toLocaleString()}</small>
                           <Button variant="link" className="text-danger p-0" size="sm" onClick={() => deleteEntry(entry.id)}>
                              <Trash2 size={14} />
                           </Button>
                        </div>
                        <Card.Text className="mb-0 text-dark" style={{ whiteSpace: 'pre-wrap' }}>
                           {entry.content}
                        </Card.Text>
                     </Card.Body>
                  </Card>
               ))}
               {entries.length === 0 && (
                  <div className="text-center text-muted py-5">
                     No entries yet. Start writing!
                  </div>
               )}
            </div>
         </Card.Body>
      </Card>
   );
};

export default Diary;
