// glass-dashboard/src/components/DashboardHome.jsx
import React from 'react';
import { Row, Col } from 'react-bootstrap';
import Calculator from './Calculator';
import TodoList from './TodoList';
import Calendar from './Calendar';

const DashboardHome = () => {
   return (
      <Row className="g-4">
         <Col lg={4} md={6}>
            <div className="h-100"><Calculator /></div>
         </Col>
         <Col lg={4} md={6}>
            <div className="h-100"><TodoList /></div>
         </Col>
         <Col lg={4} md={6}>
            <div className="h-100"><Calendar /></div>
         </Col>
      </Row>
   );
};

export default DashboardHome;

// glass-dashboard-vue/src/views/DashboardHome.vue
<template>
  <div class="q-pa-md">
    <div class="row q-col-gutter-md">
      <div class="col-12 col-md-4">
        <Calculator />
      </div>
      <div class="col-12 col-md-4">
        <TodoList />
      </div>
      <div class="col-12 col-md-4">
        <EventList />
      </div>
    </div>
  </div>
</template>

<script setup>
import Calculator from '@/components/Calculator.vue'
import TodoList from '@/components/TodoList.vue'
import EventList from '@/components/EventList.vue'
</script>
